### ISSUE TITLE
La ruta del fichero de tablas esta puesto directamente en el plugin y no se puede configurar

### ISSUE THREAD

**Issue by juanjo78git** [penicolas/utileria.vim#1]
En el plugin esta escrito directamente la ruta del fichero:
```
Linea 37:     let tablas = readfile("c:\\Users\\pnicolas\\.vim\\tmp\\tablas.txt")
```
Supongo que un pequeño cambio se puede corregir.

Un saludo.

**Comment by penicolas** [comment]
Solucionado en el commit fb198748dbcaea390104ba7799f93c780df252d9

Es necesario cambiar algunas cosas @juanjo78git, ya que el nombre de la función ha cambiado... lo siento! :(
